author: Alberto Bregliano <alberto.bregliano@pm.me>
license: MIT
Version: 0.3
Reperibilita: ./reperibilita.csv
twilioaccountsid: 
twilioauthtoken:
piattaforma: CDN
numservicedesk: 0636875015
foborainizio: 16