author: Alberto Bregliano <alberto.bregliano@pm.me>
license: MIT
Version: v2.2.4-beta
Cellpertest: "+393357291533"
Reperibilita: ./reperibilita.csv
Nagioslogfile: /var/log/nagios/nagios.log
Nagiosuser: "sauron"
twilioaccountsid: 
twilioauthtoken:
piattaforma: CDN
numservicedesk: "+39555555555"
foborainizio: 15