author: Alberto Bregliano <alberto.bregliano@pm.me>
license: MIT
Version: 0.3
Reperibilita: ./reperibilita.csv
Nagioslogfile: 
twilioaccountsid: 
twilioauthtoken:
piattaforma: CDN
numservicedesk: +390636875015
foborainizio: 14