author: Alberto Bregliano <alberto.bregliano@pm.me>
license: MIT
Version: v2.0.1-beta
Cellpertest: "+393357291533"
Reperibilita: ./reperibilita.csv
Nagioslogfile: /var/log/nagios/nagios.log
twilioaccountsid: 
twilioauthtoken:
piattaforma: CDN
numservicedesk: "+390636875015"
foborainizio: 15