language: go

go:
  - 1.10.x
  - tip

before_install:
  - go get -t -v ./...


install:
  - go get -u github.com/dave/courtney
  - go get -t -v ./...
  
script:
  - courtney

after_success:
  - bash <(curl -s https://codecov.io/bash)
